server:
  port: 8097

spring:
  application:
    name: bailian-goods
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    packages:
      trust-all: true # 信任所有包，确保消息队列在消息传输过程中，可以正确执行序列化
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.78.163.160:3306/bailian_mall?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.163.com
    # 发送者邮箱
    username: dengteng1211@163.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: RGLFLWRVHMMMZLIK
    # 端口号465或者25
    port: 465
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          ssl:
            # 这里设为true时 端口号设为 465 设为false时 端口号设为25
            enable: true
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true

  redis:
    host: 120.78.163.160
    port: 6379

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8093/eureka
