server:
  port: 8097

spring:
  application:
    name: bailian-goods

  datasource:
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/animedb?useUnicode=true&characterEncoding=utf-8&useSSL=false

  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      map-underscore-to-camel-case: true

  eureka:
    client:
      service-url:
        defaultZone: http://127.0.0.1:8093/eureka