
#???
server:
  port: 8096

#???
spring:
  application:
    name: bailian-web

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.78.163.160:3306/bailian_mall?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

  redis:
    port: 6379
    host: 120.78.163.160

#eureka??
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8093/eureka