server:
  port: 8095


spring:
  application:
    name: bailian-order


  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bailian_mall?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: admin
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    packages:
      trust-all: true # 信任所有包，确保消息队列在消息传输过程中，可以正确执行序列化
  redis:
    host: 127.0.0.1
    port: 6379

  mail:
    # 配置 SMTP 服务器地址
    host: smtp.163.com
    # 发送者邮箱
    userName: jinmutianlong@163.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: QTASXXVFTNQHEMVE

    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8093/eureka

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

wechat:
  pay:
    appId: wxab8acb865bb1637e # \u5E94\u7528id
    mchId: 11473623 # \u5546\u6237id
    mchkey: 2ab9071b06b9f739b950ddb41db2690d # \u5546\u6237\u79D8\u94A5
    orderUri: https://api.mch.weixin.qq.com/pay/unifiedorder #\u5FAE\u4FE1\u7EDF\u4E00\u4E0B\u5355\u63A5\u53E3
    notifyUri: http://w7589j.natappfree.cc/wxpayResultBack
    orderqueryUri: https://api.mch.weixin.qq.com/pay/orderquery

alipay:
  appId: 2021000119669734
  privateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCZkoZRBdGLok2iX/GS1vbWBIdxK5/+Cmsf0ahbQZgbi5/dMg9NR9kBLw8RAR2/bvCDntTzBNKKjoVvk7E7QsJMsj6tG5NqlbK1sGwGIfAlcgfgoH9cwCtbUbWzdqIk+Ns0qE0pumGuoVytTAnfHHR/WUObvsXNxbAa4nfN5S6GTG98sh7v85f9CFyQrbWNY8KQfSVxICyLgtBhzI9rFhFRDb4Arv8+XnaeWKq4b4454R3dv4yvij9IfWlCLxLZDCfO76TX9hLBhc60ziNva0WovpIcZcDl1rp8Voip3OjDuSueIgJPJHj3TZ3VNwZ1iZ964sF1lKwVj9D5d/6/CQMfAgMBAAECggEAb3MHqPspBEXoQ2OPhDoe7lhhFr9LH+jdrzzPClMDGVJt1PAEbNgsYxCMxZFizk+rmkmFT0v7o3Qk4EF1yIT9Tv24QJaXmC1FgVekPZsZlYM4tkqjw2Lu1BnrXG9G4r/7DS7quNK7GymdgWKCc3lKDjVwvDFpiZji4c/ik/izl9/xenWhv/8GvfvdCnuI2ghDOM8S4/HIk4292syirVa5pMHKRY2DV/M44w0WGBYFSzOvKEs7WAH/TzWDIbsTrW0Pwnc0KwI8NGbe+twOm82qqMGxEr+i4s+8VLoHyYgHMXelN/Fc20PTGEhYd0dC1hPZ4ZTAZZtGLLvic8Gt2ZlDCQKBgQDwvsXRzVF+Rpnfw65xQrp9bLiBiVduDgrlbwGBwOlVHpE7DRBXZ1F6kL0caoXSNpdHgvZ22Kb3PHoIe4XazcgT7puExqml7vCRSjV9l1vbZA6u/cijcCJLfEQkSsUHBC3/45ra98w37idrpnNcSthhkfJXW0wTZ27WbbQl2gbJEwKBgQCjTa9vJlJLa6deyodhEbPMCB3G711TsADq+7F70ElX8yW+lqzCLKbk+KSIgELJb42qmvRMaBHfBXKK0AEHH+Sv2AuIWoKNDMjBHOubUmNhbYiOxyHtJh1rcJ6HmOiLLuYghNr0stxbN0fgRdtikk2OmPpOx2N2QjgKvnfSGEsLRQKBgGcs62zR+KYMre+XVpCVz4Tnbl+ds8mn3QWdQGESgy2GrylGnQVIc0P6+gFOqdGAse7k8qnWiiAVXBt8jM5MOP5J2X7bAWPq9lDeI/SSRLzOsfhPLYjWCuyc8js3jB9IrEopinljj7M8rspVCMW6Eegm+1xy9TSvtHHTjExYl2XfAoGABofr1TkmH2gNyIe3BFXN6AIHFtap19f5IWyxe28oD8FkqAukmxtoDU44XlEq2p2Af+s0i/25gT7Zht2svNk0ryenxmtAP13chYSfk5Wm7dWQmY0zOSXGFW7qmCewXSiiAXjuvMyObYN3d2uzy2xod6R8ljv5KVianytg5WEdVzUCgYAr4cmlMgWQqX06qZILar+1ssIxWMFsYMUQjZB99lU5dVpYwpoKQ6jU0ukN6VisAtTDYdWZE/odlnSi/KcPJy/oHmJXvyZ6CAKxHt+Bk9uvoZc4KdjyOI5UGMDueeXlNRMZwReSrQLooP0WTrtmDtJ2Ga3ia73J56jfGsAPlnok3w==
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmZKGUQXRi6JNol/xktb21gSHcSuf/gprH9GoW0GYG4uf3TIPTUfZAS8PEQEdv27wg57U8wTSio6Fb5OxO0LCTLI+rRuTapWytbBsBiHwJXIH4KB/XMArW1G1s3aiJPjbNKhNKbphrqFcrUwJ3xx0f1lDm77FzcWwGuJ3zeUuhkxvfLIe7/OX/QhckK21jWPCkH0lcSAsi4LQYcyPaxYRUQ2+AK7/Pl52nliquG+OOeEd3b+Mr4o/SH1pQi8S2Qwnzu+k1/YSwYXOtM4jb2tFqL6SHGXA5da6fFaIqdzow7krniICTyR4902d1TcGdYmfeuLBdZSsFY/Q+Xf+vwkDHwIDAQAB
  alipublickey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr8Ru2smh0j0eUYWd6kBoCGneBJcUvtl51yoX0ApblvIqKnVzsE6W/7AM6eywGGnS1Sa6oDYC94qF6ACPRkCp5GSsPE276mkIL8YYDN1I/gTpKvpqn5yWIiKoCad37Ts4hP30NIhbihkHmGJ7D9rrxjNnq4Tbuxclo0riP3y3QIpgwTQi5Wmk3dMf63c4Dk8gbIiixf7xWrHGpCTAZ3DD8RFLwRoQuSXINohXNggFSTnCVIEiJ9p/xRDoMYY2ulWVOqD7jzYtt42YcNNeAtV5NPTlKDJhtvxHgRUXhyyhBz+/fbmQBTl4Od97OOqrmn3L4r3tk94juMnLFMbymzNMkQIDAQAB
  gateway: openapi.alipaydev.com  # 不用修改
  returnUrl: http://127.0.0.1:8095/return # 支付成功后跳转的页面，可以为空，也可以根据回调接口的判断来返回信息
  notifyUrl: http://z5cptu.natappfree.cc/notify  # 当支付成功后，支付宝的回调接口，是你本地的接口，如果没有域名的话要内网穿透
