server:
  port: 9000

spring:
  application:
    name: bailian-user

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bailian_mall?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

  redis:
    port: 6379
    host: 127.0.0.1

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8093/eureka


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/*Mapper.xml


wechat:
  auth:
    appId: wx5d1709d1caaba04b
    appSecret: 7427e4281ec8c11e357bfbb3652847f1
    codeUri: https://open.weixin.qq.com/connect/oauth2/authorize
    redirectUri: http://xdnasq.natappfree.cc/wxauthCodeBack
    accessTokenUri: https://api.weixin.qq.com/sns/oauth2/access_token
    userInfoUri: https://api.weixin.qq.com/sns/userinfo
    accessTokenRefresh: https://api.weixin.qq.com/sns/oauth2/refresh_token
    accessTokenCheck: https://api.weixin.qq.com/sns/auth

