server:
  port: 8093

spring:
  application:
    name: homework-eureka

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka
    register-with-eureka: false
    fetch-registry: false

